### ISSUE TITLE
FS2: give the possibility in the configuration to write the enriched events as JSON instead of TSV

### ISSUE THREAD

**Issue by benjben** [snowplow/enrich#394]
It will become really easy when we will use Analytics SDK's `Event`

**Comment by chuwy** [comment]
What would be the use case?

**Comment by benjben** [comment]
It would be for OSS. There seems to be a general will to transform the enriched TSV into JSON, which is performed with a lambda and the analytics SDK. If we do that directly in enrich we don't need the lambda step any more

**Comment by chuwy** [comment]
Any particular example?

I'm asking because pretty much any use case I can think of still involves SDK parsing or some kind of pre-processing. And JSON format has its own drawbacks, e.g. it's very informal - it can be lossy (`contexts_com_acme_1` kind of properties - most popular one) or lossless (with `contexts` and `derived_contexts` properties). It also has a lot of `null` properties which makes it super-bloated. If we decide to strip `null` - that's just one more JSON format to support.

I'm all for supporting something more sensible and efficient than current TSV+JSON Frankenstein, but think that we at least would have to wait until atomic event refactoring (one that would remove all non-essential properties into contexts) - after that we can support _standardized_ JSON with isomorphic Avro mappings.

**Comment by benjben** [comment]
> Any particular example?

For instance just yesterday : https://discourse.snowplowanalytics.com/t/parquet-how-to-get-it-from-enriched-stream/4445/2

> I'm asking because pretty much any use case I can think of still involves SDK parsing or some kind of pre-processing.

Once Enrich will be directly using `Event` from Analytics SDK, it will be literally 2 lines to choose to write the event as TSV or JSON, so I thought that we could provide this possibility given that some users would benefit from it.

**Comment by chuwy** [comment]
> it will be literally 2 lines

It will more than that. It's a configuration parsing, maintaining and documenting the config, it's responding OSS users why it would (not) work for their use case, it's a compatibility guarantee that we need to provide if we want to remove/change something in there.

But this is all irrelevant. What relevant is that emitting JSON will not solve anything for that user (or any other that I've seen) because they need Parquet and Parquet would require exact the preprocessing I've been talking about.

**Comment by benjben** [comment]
> It's a configuration parsing, maintaining and documenting the config

Indeed a bit more

> for that user

True for this particular use case, although it seems that he'll still use the lambda to go from TSV to JSON
