### ISSUE TITLE
No top-level "enrich" could be found in the configuration

### ISSUE THREAD

**Issue by caleb15** [snowplow/enrich#610]
**Project**: Kinesis stream enrich

**Version**: streamCommon 3.0.4

**Expected behavior**: No error

**Actual behavior**: Error

**Steps to reproduce**:

 1. Use the sample [config.kinesis.minimal.hocon](https://github.com/snowplow/enrich/blob/release/3.0.3/config/config.kinesis.minimal.hocon) configuration file
 2. Replace streamName values with your stream names
 3. Run snowplow enricher. For example, `bin/streamkinesis --config enrich-conf --resolver file:/etc/conf/resolver-conf --enrichments file:/etc/enrichments/`

Other notes: I'm on kubernetes using the snowplow/stream-enrich-kinesis:3.0.4 docker image.

`enrich` used to be a top-level field in the old v2 configuration, but the v3 configuration sample does not list enrich as a top level field. Should enrich still be a top-level field? If so, can the sample be updated please?

**Comment by caleb15** [comment]
It looks like the code still enforces enrich as a top-level field: https://github.com/snowplow/enrich/blob/8b55ec27c6e31895141f17e2cadf39ef87f75226/modules/stream/common/src/main/scala/com.snowplowanalytics.snowplow.enrich.stream/Enrich.scala#L145

**Comment by istreeter** [comment]
Hey @caleb15, thanks for reporting this.

The problem here is that the sample [config.kinesis.minimal.hocon](https://github.com/snowplow/enrich/blob/release/3.0.3/config/config.kinesis.minimal.hocon) file corresponds to the new `enrich-kinesis` asset, which is not the same as "stream enrich".

Sorry, I know the names are confusing.  There is some explanation [in the release announcement of 3.0.0](https://discourse.snowplowanalytics.com/t/enrich-3-0-0-released/6478).  Going forward, `enrich-kinesis` will get all our developer attention, and we will eventually deprecate the old stream enrich, so it's worth making the switch.

If you run the `enrich-kinesis` docker image then you should find the sample configuration works perfectly:

```
docker run \
  -v $PWD/config:/snowplow/config \
  snowplow/snowplow-enrich-kinesis:latest \
  --config /snowplow/config/config.kinesis.minimal.hocon \
  --iglu-config /snowplow/config/iglu_resolver.json \
  --enrichments /snowplow/config/enrichments
```

We clearly made a mistake in the `3.x` release that we removed the valid example config file for the old stream enrich -- sorry about that.  If you still need to see an example to a valid stream enrich config file then [here is a link](https://github.com/snowplow/enrich/blob/2.0.7/config/config.hocon.sample) to a previous release.

**Comment by caleb15** [comment]
Thanks! I switched to the new enrichment image and so far it's working :) 

2.0.7 is not a option for me, unfortunately, because we are using Kubernetes service accounts linked to IAM roles and I think AWS STS jar is needed for that feature. I'm presuming simply injecting the jar into the image wouldn't be enough to make it work, hence why I tried upgrading.
